api/urls.py
from .views import EventApiView, EventDetailApiView, SermonApiView, SermonDetailApiView
from django.urls import path

urlpatterns = [

    # Sermon endpoints
    path('sermons', SermonApiView.as_view()),
    path('sermons/<int:pk>/', SermonDetailApiView.as_view()),


    # Event endpoints
    path('events', EventApiView.as_view()),
    path('events/<int:pk>/', EventDetailApiView.as_view()),

]

gway/urls.py
from api.router import router

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView


urlpatterns = [

    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('contact/', include('contact.urls')),
    path('events/', include('events.urls')),
    path('location/', TemplateView.as_view(
                      template_name='location/index.html'), name='location'),
    path('sermons/', include('sermons.urls')),
    path('subscribe/', include('subscribe.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

sermons/urls.py
from django.urls import path

from . import views

app_name = 'sermons'

urlpatterns = [
    # /sermons/
    path('', views.index, name='index'),
    # /sermons/1 where number is id
    path('<int:pk>/', views.SermonDetailView.as_view(), name='detail'),
]

sermons/models.py
import audioread

from django.db import models


class Sermons(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateField()
    description = models.TextField()
    file = models.FileField(max_length=1000)

    class Meta:
        permissions = (
                ('can_submit', "Can submit a new Sermon"),
            )
        verbose_name = 'Sermon'

    def __str__(self):
        return self.title

    def get_duration(self):
        f = audioread.audio_open(self.file.path)
        duration = round(f.duration/60)
        return duration

sermons/forms.py
from django.forms import ModelForm

from .models import Sermons


class SermonForm(ModelForm):
    class Meta:
        model = Sermons
        fields = ['title', 'date', 'description', 'file']

sermons/views.py
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import DetailView

from .models import Sermons


def index(request):
    sermon_objs = Sermons.objects
    all_sermons = sermon_objs.all()
    sermon_count = all_sermons.count()
    sermons_ordered_by_date = sermon_objs.order_by('date')

    search_text = None
    search_result_count = None

    if 'search' in request.GET:
        search_text = request.GET['search']
        all_sermons = all_sermons.filter(
            Q(description__icontains=search_text) |
            Q(title__icontains=search_text)
        )
        search_result_count = all_sermons.count()

        if search_result_count:
            if search_result_count > 1:
                search_result_count = '{} results.'.format(search_result_count)
            else:
                search_result_count = '{} result.'.format(search_result_count)
        else:
            messages.success(request, "Your search yielded no results.",
                                      extra_tags="message_failure")
            all_sermons = Sermons.objects.all()

    context = {
        'all_sermons': all_sermons,
        'first_sermon': sermons_ordered_by_date[0],
        'last_sermon': sermons_ordered_by_date[sermon_count-1],
        'search_text': search_text,
        'search_result_count': search_result_count,
        'sermon_count': sermon_count,
    }

    return render(request, 'sermons/index.html', context)


class SermonDetailView(DetailView):
    template_name = 'sermons/details.html'
    context_object_name = 'sermon'
    queryset = Sermons.objects.all()

    def get_context_data(self, **kwargs):
        context = super(SermonDetailView, self).get_context_data(**kwargs)
        return context

sermons/templates/sermons/details.html
{% extends 'base.html' %}

{% block header %}
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'sermons/css/style-details.css' %}">
  <script src="{% static 'sermons/js/script.js' %}"></script>
{% endblock %}

{% block body %}

<div class="wrapper">

    <h1 class="header">{{ sermon.title }}</h1>

    <h3 class="date">{{ sermon.date }}</h3>

    <div class="audio">
      		<audio controls id="track" preload="metadata">
      			<source src="{{ sermon.file.url }}" type="audio/mpeg">
      		</audio>
    </div>

</div>
<div class="description">
    <p>{{ sermon.get_duration }} minutes | {{ sermon.file.size|filesizeformat }}</p>
    <p>{{ sermon.description }}</p>
</div>

{% load static %}
  <script src="{% static 'sermons/js/script.js' %}"></script>

{% endblock %}

sermons/templates/sermons/index.html
{% extends 'base.html' %}

{% block header %}
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'sermons/css/style-sermons.css' %}">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
	<script src="{% static 'sermons/js/script.js' %}"></script>
{% endblock %}

{% block body %}
<div class="wrapper">
		<div class="wrapper-header">
			<h2 class="header">Sermon Archive</h2>
		</div>

		<div class="wrapper-search">
			<div id="search-bar">
				<form>
				  <div class="input-group search-bar">
					    <input type="search" class="form-control" name="search" id="myInput" placeholder="Search">
					    <div class="input-group-btn">
					    	<button class="btn btn-primary" type="submit">
					        	<i class="fas fa-search"></i>
					      	</button>
				    	</div>
				  </div>
				</form>
			</div>
		</div>

		<div class="wrapper-messages">
			{% if messages %}
				<ul class="messages">
					{% for message in messages %}
						<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
					{% endfor %}
				</ul>
			{% else %}
				{% if 'search' in request.GET %}
					<p>Your search for "<em>{{ search_text }}</em>" yielded {{ search_result_count }}</p>
				{% endif %}
			{% endif %}
		 </div>

		<div class="wrapper-table">
			{% if sermon_count > 1 %}
				<p>A total of {{ sermon_count }} sermons exist in the archive, dating from
					{{ first_sermon.date }} to {{ last_sermon.date }}.</p>
			{% endif %}
			<table id="sermons" class="">
				<tr>
					<th onclick="sortTable(0)">Title</th>
					<th onclick="sortTable(0)">Date</th>
					<th>Length</th>
					<th>File</th>
				</tr>
				<tbody id="myTable">
					{% for sermon in all_sermons %}
					<tr class="tr">
						<td>
							<a id="title_link" href="{% url 'sermons:detail' sermon.id %}">{{ sermon.title }}</a>
						</td>
						<td>{{ sermon.date }}</td>
							<td>{{ sermon.get_duration }} minutes</td>
						<td><a class="file" href="{{ sermon.file.url }}" download><img id="download-icon" src="{% static 'sermons/img/download.png' %}"></a></td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		</div>

	</div>
{% endblock %}