about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [

    path('', views.index, name='index'),
]

api/urls.py
from .views import EventApiView, EventDetailApiView, SermonApiView, SermonDetailApiView
from django.urls import path

urlpatterns = [

    # Sermon endpoints
    path('sermons', SermonApiView.as_view()),
    path('sermons/<int:pk>/', SermonDetailApiView.as_view()),


    # Event endpoints
    path('events', EventApiView.as_view()),
    path('events/<int:pk>/', EventDetailApiView.as_view()),

]

contact/urls.py
from django.urls import path

from . import views

app_name = 'contact'

urlpatterns = [
    # /contact/
    path('', views.index.as_view(), name='index'),

]

events/urls.py
from django.urls import path

from . import views

app_name = 'events'

urlpatterns = [
    # /events/
    path('', views.index, name='index'),
    # /events/1 where number is id
    # path('<int:pk>/', views.EventDetailView.as_view(), name='detail'),
    path('<int:year>/<int:month>/<int:day>/<int:pk>',
         views.EventDetailView.as_view(), name='detail'),
]

gway/urls.py
from api.router import router

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView


urlpatterns = [

    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('contact/', include('contact.urls')),
    path('events/', include('events.urls')),
    path('location/', TemplateView.as_view(
                      template_name='location/index.html'), name='location'),
    path('sermons/', include('sermons.urls')),
    path('subscribe/', include('subscribe.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views


app_name = 'home'

urlpatterns = [
    # /events/
    path('', views.index, name='index'),
]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-128591488-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-128591488-1');
    </script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Welcome to Gateway Baptist Church, located in Valdosta, Georgia">
    <meta name="author" content="">
    
    {% load static %}
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/all.js" integrity="sha384-xymdQtn1n3lH2wcu0qhcdaOpQwyoarkgLVxC/wZ5q7h9gHtxICrpcaSUfygqZGOe" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Lato:700" rel="stylesheet">
    <link rel="stylesheet" href="https://getbootstrap.com/docs/4.1/dist/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/footer-stylesheet.css' %}"><!--stylesheet for footer-->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src="https://kit.fontawesome.com/390e177c68.js" crossorigin="anonymous"></script>



    <title>Gateway Baptist Church</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style-global.css' %}">

    {% block header %}
    {% endblock %}
  </head>
  <body>

    <header>
      {% include 'navbar.html' %}
    </header>

      {% block body %}
      {% endblock %}
	  
		<div class="contentF"></div> <!--Used to make the footer stick to the bottom--> 
	<footer>
		{% include 'footer.html' %}
	</footer>

  </body>
</html>

templates/footer.html
    <div class="footerContent">
        <div class="logoPlaced">
        {% load static %}
        <img src="{% static 'img/Logo.png' %}">
            <div class="logoText" >
                <h2>GATE<span style="color:#cfa7e8">WAY</span><br> BAPTIST CHURCH</h2>
                <h4 style="clear: left; margin: 5px;">17825 Valdosta Hwy, Valdosta, GA 31602</h4>
            </div>
        </div>


        <div class="services footerMain">
            <h3>Services</h3>
            <li>Sunday School 9:45am </li>
            <li>Sunday worship 11am & 6pm</li>
            <li>Wednesday worship 7:30pm </li>
        </div>

        <div class="contactUs footerMain">
            <h3>Contact us</h3>
            <li><a href="mailto:gwaybaptist@gmail.com">gwaybaptist@gmail.com</a></li>
            <li><a href="tel:+2292418844">(229) 241-8844</a></li>
            <li>
                <a
                href="https://www.facebook.com/pages/Gateway-Baptist-Church/266605370109693?rf=743985075635002"
                 style="font-size:2em"><i class="fab fa-facebook"></i>
                </a>
            </li>
        </div>
    </div>

        <div  class="lowerFooter">
                <i class="leftAlign">Copyright &copy; 2020 Contact <a>Webmaster</a></i>
                <i class="rightAlign"><a href="{% url 'admin:index' %}"> Admin login</a></i>
        </div>

templates/index.html
{% extends 'base.html' %}

	{% block header %}
	{% load static %}
	<link href="{% static 'css/index-style.css' %}" rel="stylesheet">
    <link href="{% static 'css/index-events.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans&display=swap" rel="stylesheet">
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v6.0"></script>
	{% endblock %}


{% block body %}

  <header id="showcase" class="grid">
    <div class="bg-image"></div>
    <div class="content-wrap">
      <h1 id="bg-image-header">Welcome to Gateway</h1>

      <a href="#section-a" class="btn-1 btn">You're Invited</a>

    </div>
  </header>

  <!-- Main Area -->
  <main id="main">
    <!-- Section A -->
	    <section id="section-a" class="grid">
	      <div class="content-wrap">
	        <h1 class="content-title">Service Times</h1>

	        <div class="content-service-wrapper">
	          <table class="content-table">
				<tr>
					<th>Sunday</th>
					<th></th>
					<th>Wednesday</th>
				</tr>
                <tr>
					<td>Sunday School</td>
					<td></td>
					<!-- <td>Evening Worship</td> -->
				</tr>
				<tr>
					<td>9:45 am</td>
					<td></td>
					<td>Evening Worship</td>
				</tr>
				<tr>
					<td>Morning Worship</td>
                    <td></td>
                    <td>7:30 pm</td>
				</tr>
				<tr>
					<td>11 am</td>
                    <td></td>

				</tr>
				<tr>
					<td>Evening Worship</td>
				</tr>
				<tr>
					<td>6 pm</td>
				</tr>
	          </table>
			</div>
	        </div>
	    </section>

      {% if redirect_anchor %}
      <script type='text/javascript'>
      $(document).ready(function(){
          window.location = '#{{ redirect_anchor }}'
      });
      </script>
      {% endif %}

      <section id="section-f" class="grid">
        <div class="content-wrap">
          <h2 class="content-title">Subscribe to our Newsletter</h2>
          <p style="margin-bottom:15px">Stay up to date on upcoming events, prayer requests, and more.
          </p>

            <form method="POST">
              {% csrf_token %}
              <div class = "form-group">

              <div>
                {{ form.as_p }}
                <input type="submit" id="newsletter-submit-btn" name="" value="Subscribe" style="
                  background-color: #4CAF50; /* Green */
                  border: none;
                  color: white;
                  /*padding: 15px 42px;*/
                  padding: 15px 45px 15px 45px;
                  text-align: center;
                  text-decoration: none;
                  display: inline-block;
                  font-size: 16px;">
              </div>

            </form>

        </div>
      </section>

	<!-- Section B --->
	<h1 class="content-title">Upcoming events</h1>
	<section id="section-b" class="grid">
		<ul>
			{% for event in three_events %}
			<li>
                <div id="test_grid">
                    <div id="header">
                      <a href="{% url 'events:detail' event.date.year event.date.month event.date.day event.pk %}">{{ event.name }}</a>
                    </div>
                    <div id="date-card">
                    <div class="month">
                        {{ event.date|date:'F' }}
                    </div>
                    <div class="day">
                        {{ event.date.day }}
                    </div>
                </div>
            </div>
			</li>
			{% endfor %}
      </ul>
    </section>

  <!-- Section C --->
    <section id="section-c" class="grid">
      <div class="content-wrap">
        <h2 class="content-title">About our Church</h2>
					<div class="w3-panel w3-leftbar w3-light-grey">
					  <p class="w3-xlarge w3-serif">
							<i class="fa fa-quote-left w3-xxlarge w3-opacity"></i>
					  <i>"Surely the Lord is in this place... This is none other but the house of God
							, and this is the gate of heaven."</i><i class="fa fa-quote-right w3-xxlarge w3-opacity"></i>
						</p>

					  <p>Genesis 28:16–17</p>
					</div>
      </div>
    </section>

    <!-- Section D --->
    <section id="section-d" class="grid">
      <div class="box">
        <h2 class="content-title">Listen to Sermons</h2>
        <p>Visit our <a href="{% url 'sermons:index' %}">Sermon Archive</a> to listen to previous sermons delivered at
				 Gateway Baptist Church </p>
      </div>
			<div class="box">
        <h2 class="content-title">Easter Sermon</h2>
        <div class="fb-video" data-href="https://www.facebook.com/jack.seiverd/videos/10212430107507560/" data-show-text="false" data-width=""><blockquote cite="https://developers.facebook.com/jack.seiverd/videos/10212430107507560/" class="fb-xfbml-parse-ignore"><a href="https://developers.facebook.com/jack.seiverd/videos/10212430107507560/"></a><p>Gateway Easter message 4-12-20</p>Posted by <a href="https://www.facebook.com/jack.seiverd">Jack H. Seiverd</a> on Sunday, April 12, 2020</blockquote></div>
      </div>
    </section>


  </main>



{% endblock %}

templates/navbar.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/nav-style.css' %}">

  <nav class="navbar navbar-expand-md navbar-dark fixed-top back">
    <a class="navbar-brand" href="{% url 'home:index' %}">Gateway Baptist</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        <div class="dropdown">
          <div class=" dropdown-toggle min" data-toggle="dropdown">About</a>
        </div>
          <ul class="dropdown-menu">
            <li><a href="{% url 'about:index' %}">Our Church</a></li>
            <hr>
            <li><a href="#">Ministries</a></li>
          </ul>
        </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'sermons:index' %}">Sermons</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'location' %}">Location</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'events:index' %}">Events</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact:index' %}">Contact</a>
        </li>
      </ul>
      {% if user.is_authenticated %}
        <ul class="nav navbar-nav navbar-right ml-auto">
          <li class="nav-item">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">
            {{ user.username }}
            </a>
            <ul class="dropdown-menu" style="right: 0; left:auto;">
              <li><a href="{% url 'admin:index' %}">Dashboard</a></li>
              <hr>
              <li><a href="{% url 'admin:sermons_sermons_add' %}">Add Sermon</a></li>
              <hr>
              <li><a href="{% url 'admin:events_event_add' %}">Add Event</a></li>
              <hr>
              <li><a href="{% url 'admin:contact_contact_changelist' %}">View Contacts</a></li>
              <hr>
              <li><a href="{% url 'logout' %}">Log out</a></li>
            </ul>
          </li>
        </ul>
      {% else %}
      {% endif %}
    </div>
  </nav>